baseURL = 'https://viswabalaji.github.io/'
languageCode = 'en-us'
title = 'Viswa Balaji'
theme = 'hugo-blog-awesome'

[services.googleAnalytics]
  id = 'G-R17Z0BWKKN'

[params]
  sitename = "Viswa Balaji"
  description = "Writing on technical topics, poetry, short stories, and bookshelf"
  mainSections = ['technical', 'poetry', 'stories', 'bookshelf']
  defaultColor = "auto"
  toc = true
  tocOpen = true
  goToTop = true

  [params.author]
    name = "Viswa Balaji"
    intro = "Viswa Balaji"
    description = "Writing on technical topics, poetry, short stories, and bookshelf"


[[params.socialIcons]]
  name = "github"
  url = "https://github.com/viswabalaji"

[menu]
  [[menu.main]]
    identifier = "technical"
    name = "Technical"
    url = "/technical/"
    weight = 10

  [[menu.main]]
    identifier = "poetry"
    name = "Poetry"
    url = "/poetry/"
    weight = 20

  [[menu.main]]
    identifier = "stories"
    name = "Stories"
    url = "/stories/"
    weight = 30

  [[menu.main]]
    identifier = "bookshelf"
    name = "Bookshelf"
    url = "/bookshelf/"
    weight = 35

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    lineNumbersInTable = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
