baseURL = 'https://viswabalaji.github.io/'
languageCode = 'en-us'
title = 'Viswa Balaji'
theme = 'hugo-blog-awesome'

[services.googleAnalytics]
  id = 'G-R17Z0BWKKN'

[params]
  sitename = "Viswa Balaji"
  description = "Writing on technical topics, poetry, and short stories"
  mainSections = ['technical', 'poetry', 'stories']
  defaultColor = "auto"
  toc = true
  tocOpen = true
  goToTop = true

  [params.author]
    name = "Viswa Balaji"
    intro = "Viswa Balaji"
    description = "Writing on technical topics, poetry, and short stories"


[[params.socialIcons]]
  name = "github"
  url = "https://github.com/viswabalaji"

[menu]
  [[menu.main]]
    identifier = "technical"
    name = "Technical"
    url = "/technical/"
    weight = 10

  [[menu.main]]
    identifier = "poetry"
    name = "Poetry"
    url = "/poetry/"
    weight = 20

  [[menu.main]]
    identifier = "stories"
    name = "Stories"
    url = "/stories/"
    weight = 30

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    lineNumbersInTable = true
